package enumeraciones;

public enum Pais {
	AFGANISTÁN, ALBANIA, ALEMANIA, ANDORRA, ANGOLA, ARABIA, 
	ARGELIA, ARGENTINA, ARMENIA, AUSTRALIA, AUSTRIA, AZERBAIYÁN, BAHAMAS, BANGLADÉS, BARBADOS, BARÉIN, 
	BÉLGICA, BELICE, BENÍN, BIELORRUSIA, BIRMANIA, BOLIVIA, BOSNIAYHERZEGOVINA, BOTSUANA, BRASIL, 
	BRUNÉI, BULGARIA, BURKINAFASO, BURUNDI, BUTÁN, CABOVERDE, CAMBOYA, CAMERÚN, CANADÁ, CATAR, CHAD, CHILE, CHINA, 
	CHIPRE, COLOMBIA, COMORAS, COREADELNORTE, COREADELSUR, COSTADEMARFIL, COSTARICA,
	CROACIA, CUBA, DINAMARCA, DOMINICA, ECUADOR, EGIPTO, SALVADOR, EMIRATOSÁRABESUNIDOS, ERITREA, ESLOVAQUIA, 
	ESLOVENIA, ESPAÑA, ESTADOSUNIDOS, ESTONIA, ETIOPÍA, FILIPINAS, FINLANDIA, FIYI, FRANCIA, GABÓN, GAMBIA, GEORGIA,
	GHANA, GRANADA, GRECIA, GUATEMALA, GUYANA, GUINEAECUATORIAL, HAITÍ, HONDURAS, HUNGRÍA, INDIA,
	INDONESIA, IRAK, IRÁN, IRLANDA, ISLANDIA, ISLASMARSHALL, SALOMÓN, ISRAEL, ITALIA, JAMAICA, JAPÓN, JORDANIA, 
	KAZAJISTÁN, KENIA, KIRGUISTÁN, KIRIBATI, KUWAIT, LAOS, LESOTO, LETONIA, LÍBANO, LIBERIA, LIBIA, LIECHTENSTEIN, LITUANIA, 
	LUXEMBURGO, MACEDONIA, MADAGASCAR, MALASIAMALAUI, MALDIVAS, MALÍ, MALTA, MARRUECOS, MAURICIO, MAURITANIA, 
	MÉXICO, MICRONESIA, MOLDAVIA, MÓNACO, MONGOLIA, MONTENEGRO, MOZAMBIQUE, NAMIBIA, NAURU, NEPAL, NICARAGUA, NÍGER, NIGERIA, 
	NORUEGA, NUEVA, ZELANDA, OMÁN, PAÍSESBAJOS, PAKISTÁN, PALAOS, PANAMÁ, PAPÚANUEVA, 
	GUINEA, PARAGUAY, PERÚ, POLONIA ,PORTUGAL, REINOUNIDO,  REPÚBLICACHECA ,REPÚBLICADELCONGO, 
	 REPÚBLICADOMINICANA, RUANDA, RUMANÍA, RUSIA, SAMOA,  SANMARINO, 
	 SENEGAL, SERBIA, SEYCHELLES, SIERRALEONA, SINGAPUR,
	SIRIA, SOMALIA, SRILANKA, SUAZILANDIA, SUDÁFRICA, SUDÁN, SUECIA, SUIZA, SURINAM, TAILANDIA, TANZANIA, 
	TAYIKISTÁN,  TOGO, TONGA, TRINIDADYTOBAGO, TÚNEZ, TURKMENISTÁN, TURQUÍA, TUVALU, UCRANIA, UGANDA, URUGUAY,
	UZBEKISTÁN, VANUATU, VENEZUELA, VIETNAM, YEMEN, YIBUTI, ZAMBIA, ZIMBABUE;
}
